# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 693)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dirLabel = QtWidgets.QLabel(self.centralWidget)
        self.dirLabel.setObjectName("dirLabel")
        self.horizontalLayout_4.addWidget(self.dirLabel)
        self.loadDirlineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.loadDirlineEdit.setObjectName("loadDirlineEdit")
        self.horizontalLayout_4.addWidget(self.loadDirlineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.clearButton = QtWidgets.QPushButton(self.centralWidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_5.addWidget(self.clearButton)
        self.browseButton = QtWidgets.QPushButton(self.centralWidget)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_5.addWidget(self.browseButton)
        self.loadButton = QtWidgets.QPushButton(self.centralWidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_5.addWidget(self.loadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filenameLabel = QtWidgets.QLabel(self.centralWidget)
        self.filenameLabel.setObjectName("filenameLabel")
        self.horizontalLayout_7.addWidget(self.filenameLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.indexSpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.indexSpinBox.setMaximum(1000)
        self.indexSpinBox.setObjectName("indexSpinBox")
        self.horizontalLayout_7.addWidget(self.indexSpinBox)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.totalLabel = QtWidgets.QLabel(self.centralWidget)
        self.totalLabel.setObjectName("totalLabel")
        self.horizontalLayout_7.addWidget(self.totalLabel)
        self.displayButton = QtWidgets.QPushButton(self.centralWidget)
        self.displayButton.setObjectName("displayButton")
        self.horizontalLayout_7.addWidget(self.displayButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.frameGraphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.frameGraphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frameGraphicsView.setMouseTracking(True)
        self.frameGraphicsView.setObjectName("frameGraphicsView")
        self.verticalLayout.addWidget(self.frameGraphicsView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minFrameLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minFrameLabel.sizePolicy().hasHeightForWidth())
        self.minFrameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.minFrameLabel.setFont(font)
        self.minFrameLabel.setObjectName("minFrameLabel")
        self.horizontalLayout_3.addWidget(self.minFrameLabel)
        self.frameHorizontalScrollBar = QtWidgets.QScrollBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHorizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.frameHorizontalScrollBar.setSizePolicy(sizePolicy)
        self.frameHorizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.frameHorizontalScrollBar.setObjectName("frameHorizontalScrollBar")
        self.horizontalLayout_3.addWidget(self.frameHorizontalScrollBar)
        self.maxFrameLabel = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.maxFrameLabel.setFont(font)
        self.maxFrameLabel.setObjectName("maxFrameLabel")
        self.horizontalLayout_3.addWidget(self.maxFrameLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.stenosisLabelButton = QtWidgets.QRadioButton(self.centralWidget)
        self.stenosisLabelButton.setObjectName("stenosisLabelButton")
        self.horizontalLayout.addWidget(self.stenosisLabelButton)
        self.endPointButton = QtWidgets.QRadioButton(self.centralWidget)
        self.endPointButton.setObjectName("endPointButton")
        self.horizontalLayout.addWidget(self.endPointButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.nextButton = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dirLabel.setText(_translate("MainWindow", "DIR"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.filenameLabel.setText(_translate("MainWindow", "File Name"))
        self.totalLabel.setText(_translate("MainWindow", "Maxnum"))
        self.displayButton.setText(_translate("MainWindow", "Display"))
        self.minFrameLabel.setText(_translate("MainWindow", "1"))
        self.maxFrameLabel.setText(_translate("MainWindow", "80"))
        self.stenosisLabelButton.setText(_translate("MainWindow", "Stnosis Labeling"))
        self.endPointButton.setText(_translate("MainWindow", "End point Labeling"))
        self.nextButton.setText(_translate("MainWindow", "Save / Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
