# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 854)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.settingGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.settingGroupBox.setObjectName("settingGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dirLabel = QtWidgets.QLabel(self.settingGroupBox)
        self.dirLabel.setObjectName("dirLabel")
        self.horizontalLayout_4.addWidget(self.dirLabel)
        self.loadDirlineEdit = QtWidgets.QLineEdit(self.settingGroupBox)
        self.loadDirlineEdit.setObjectName("loadDirlineEdit")
        self.horizontalLayout_4.addWidget(self.loadDirlineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.clearButton = QtWidgets.QPushButton(self.settingGroupBox)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_5.addWidget(self.clearButton)
        self.browseButton = QtWidgets.QPushButton(self.settingGroupBox)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_5.addWidget(self.browseButton)
        self.loadButton = QtWidgets.QPushButton(self.settingGroupBox)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_5.addWidget(self.loadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.settingGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.saveDirLineEdit = QtWidgets.QLineEdit(self.settingGroupBox)
        self.saveDirLineEdit.setObjectName("saveDirLineEdit")
        self.horizontalLayout_6.addWidget(self.saveDirLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.settingGroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.stenosisLabelButton = QtWidgets.QRadioButton(self.settingGroupBox)
        self.stenosisLabelButton.setObjectName("stenosisLabelButton")
        self.horizontalLayout.addWidget(self.stenosisLabelButton)
        self.endPointButton = QtWidgets.QRadioButton(self.settingGroupBox)
        self.endPointButton.setObjectName("endPointButton")
        self.horizontalLayout.addWidget(self.endPointButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.outputClearButton = QtWidgets.QPushButton(self.settingGroupBox)
        self.outputClearButton.setObjectName("outputClearButton")
        self.horizontalLayout_8.addWidget(self.outputClearButton)
        self.browseSetButton = QtWidgets.QPushButton(self.settingGroupBox)
        self.browseSetButton.setObjectName("browseSetButton")
        self.horizontalLayout_8.addWidget(self.browseSetButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.settingGroupBox)
        self.disaplayGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.disaplayGroupBox.setObjectName("disaplayGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.disaplayGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.disaplayGroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.filenameLabel = QtWidgets.QLabel(self.disaplayGroupBox)
        self.filenameLabel.setObjectName("filenameLabel")
        self.horizontalLayout_7.addWidget(self.filenameLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.indexSpinBox = QtWidgets.QSpinBox(self.disaplayGroupBox)
        self.indexSpinBox.setMaximum(1000)
        self.indexSpinBox.setObjectName("indexSpinBox")
        self.horizontalLayout_7.addWidget(self.indexSpinBox)
        self.label_4 = QtWidgets.QLabel(self.disaplayGroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.disaplayGroupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.totalLabel = QtWidgets.QLabel(self.disaplayGroupBox)
        self.totalLabel.setObjectName("totalLabel")
        self.horizontalLayout_7.addWidget(self.totalLabel)
        self.label_6 = QtWidgets.QLabel(self.disaplayGroupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.frameGraphicsView = QtWidgets.QGraphicsView(self.disaplayGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGraphicsView.sizePolicy().hasHeightForWidth())
        self.frameGraphicsView.setSizePolicy(sizePolicy)
        self.frameGraphicsView.setMinimumSize(QtCore.QSize(512, 512))
        self.frameGraphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frameGraphicsView.setMouseTracking(True)
        self.frameGraphicsView.setObjectName("frameGraphicsView")
        self.verticalLayout_3.addWidget(self.frameGraphicsView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minFrameLabel = QtWidgets.QLabel(self.disaplayGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minFrameLabel.sizePolicy().hasHeightForWidth())
        self.minFrameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.minFrameLabel.setFont(font)
        self.minFrameLabel.setObjectName("minFrameLabel")
        self.horizontalLayout_3.addWidget(self.minFrameLabel)
        self.frameHorizontalScrollBar = QtWidgets.QScrollBar(self.disaplayGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHorizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.frameHorizontalScrollBar.setSizePolicy(sizePolicy)
        self.frameHorizontalScrollBar.setMaximum(100)
        self.frameHorizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.frameHorizontalScrollBar.setObjectName("frameHorizontalScrollBar")
        self.horizontalLayout_3.addWidget(self.frameHorizontalScrollBar)
        self.maxFrameLabel = QtWidgets.QLabel(self.disaplayGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.maxFrameLabel.setFont(font)
        self.maxFrameLabel.setObjectName("maxFrameLabel")
        self.horizontalLayout_3.addWidget(self.maxFrameLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.disaplayGroupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clearDotsButton = QtWidgets.QPushButton(self.centralWidget)
        self.clearDotsButton.setObjectName("clearDotsButton")
        self.horizontalLayout_2.addWidget(self.clearDotsButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.previousButton = QtWidgets.QPushButton(self.centralWidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_2.addWidget(self.previousButton)
        self.saveButton = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.nextButton = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settingGroupBox.setTitle(_translate("MainWindow", "I/O Setting"))
        self.dirLabel.setText(_translate("MainWindow", "Load Dir"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.label.setText(_translate("MainWindow", "Save Dir"))
        self.label_2.setText(_translate("MainWindow", "Annotation Type:"))
        self.stenosisLabelButton.setText(_translate("MainWindow", "Stnosis Labeling"))
        self.endPointButton.setText(_translate("MainWindow", "Catheter End Labeling"))
        self.outputClearButton.setText(_translate("MainWindow", "Clear"))
        self.browseSetButton.setText(_translate("MainWindow", "Browse/Set"))
        self.disaplayGroupBox.setTitle(_translate("MainWindow", "Frame Display"))
        self.label_3.setText(_translate("MainWindow", "File Name:"))
        self.filenameLabel.setText(_translate("MainWindow", "File Name"))
        self.label_4.setText(_translate("MainWindow", "th"))
        self.label_5.setText(_translate("MainWindow", "out of"))
        self.totalLabel.setText(_translate("MainWindow", "Max"))
        self.label_6.setText(_translate("MainWindow", ".dcm files"))
        self.minFrameLabel.setText(_translate("MainWindow", "1"))
        self.maxFrameLabel.setText(_translate("MainWindow", "80"))
        self.clearDotsButton.setText(_translate("MainWindow", "Clear Dots"))
        self.previousButton.setText(_translate("MainWindow", "Previous"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.nextButton.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
